backend:
  name: github
  repo: skdidbstkd/hanssemdesignbuff
  branch: main
  base_url: https://designbuff-oauth-vercel.vercel.app
  auth_endpoint: /api/auth

site_url: https://skdidbstkd.github.io/hanssemdesignbuff

media_folder: "assets/uploads"
public_folder: "/hanssemdesignbuff/assets/uploads"

publish_mode: editorial_workflow
locale: "ko"

collections:
  - name: "posts"
    label: "테스트 글"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "본문", name: "body", widget: "markdown" }
