backend:
  name: github
  repo: skdidbstkd/hanssemdesignbuff
  branch: main
  base_url: https://netlify-cms-github-oauth-provider-r.vercel.app
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://skdidbstkd.github.io/hanssemdesignbuff
display_url: https://skdidbstkd.github.io/hanssemdesignbuff

logo_url: /assets/uploads/logo.png

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "designers"
    label: "Designers"
    folder: "content/designers"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Profile Image", name: "profile_image", widget: "image" }
      - { label: "Bio", name: "bio", widget: "markdown" }
